draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30
  combo_w: 28
  combo_h: 26
  key_rx: 6
  key_ry: 6
  outer_pad_w: 30
  outer_pad_h: 56
  line_spacing: 1.2
  arc_radius: 6
  append_colon_to_layer_header: true
  style_layer_activators: true

parse_config:
  raw_binding_map:
    "&bootloader": "⏻"
    "&studio_unlock": "Studio 🔓"
    "&a_circ": â
    "&a_grave": à
    "&e_acute": é
    "&e_grave": è
    "&e_circ": ê
    "&i_circ": î
    "&i_trema": ï
    "&o_circ": ô
    "&u_circ": û
    "&u_grave": ù
    "&kp RA(C)": ç
    "&kp LA(Q)": œ
    "&kp LA(U)": ¨
    "&kp LA(SQT)": æ
    "&kp MEH(GRAVE)": "≡←"
    "&kp MEH(UP)": "◎↑"
    "&kp MEH(MINUS)": "≡→"
    "&kp MEH(SINGLE_QUOTE)": "◇←"
    "&kp MEH(LBKT)": "▣→"
    "&kp MEH(LEFT)": "◎←"
    "&kp MEH(DOWN)": "◎↓"
    "&kp MEH(RIGHT)": "◎→"
    "&kp MEH(RBKT)": "◇→"
    "&kp MEH(SLASH)": "▱"
    "&kp MEH(EQUAL)": "≡"
    "&kp MEH(BACKSLASH)": "⛶"
    "&kp MEH(F1)": "◇1"
    "&kp MEH(F2)": "◇2"
    "&kp MEH(F3)": "◇3"
    "&kp MEH(F4)": "◇4"
    "&kp MEH(F5)": "◇5"
    "&kp MEH(F6)": "◇6"
    "&kp MEH(F7)": "◇7"
    "&kp MEH(F8)": "◇8"
    "&kp MEH(F9)": "◇9"
    "&kp MEH(F10)": "◇10"
  layer_legend_map:
    Nav: "⌖"
    Math: "∑"
    Symbols: "#"
    Fn: "ƒ"
    Hyper: "✦"
  modifier_fn_map:
    left_ctrl: "⌃"
    right_ctrl: "⌃"
    left_shift: "⇧"
    right_shift: "⇧"
    left_alt: "⌥"
    right_alt: "⌥"
    left_gui: "◆"
    right_gui: "◆"
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: "✦"
      left_ctrl+left_alt+left_shift: "✣"
  zmk_keycode_map:
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: "$"
    DLLR: "$"
    PERCENT: "%"
    PRCNT: "%"
    CARET: "^"
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: "("
    LPAR: "("
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    EQUAL: "="
    PLUS: "+"
    KP_PLUS: "+"
    KP_DIVIDE: "÷"
    MINUS: "-"
    UNDERSCORE: "_"
    UNDER: "_"
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: "\\"
    BSLH: "\\"
    PIPE: "|"
    NON_US_BACKSLASH: "\\"
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ";"
    SEMI: ";"
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: "<"
    LT: "<"
    PERIOD: "."
    DOT: "."
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
    LCTRL: "⌃"
    RCTRL: "⌃"
    LSHFT: "⇧"
    RSHIFT: "⇧"
    LALT: "⌥"
    RALT: "⌥"
    LGUI: "◆"
    RGUI: "◆"
    LCMD: "◆"
    SPACE: "␠"
    TAB: "⇥"
    BACKSPACE: "⌫"
    BSPC: "⌫"
    DELETE: "⌦"
    DEL: "⌦"
    RETURN: "⏎"
    RET: "⏎"
    ENTER: "⏎"
    ESCAPE: "⎋"
    ESC: "⎋"
    HOME: "↖"
    END: "↘"
    PAGE_UP: "⇞"
    PAGE_DOWN: "⇟"
    UP: "↑"
    DOWN: "↓"
    LEFT: "←"
    RIGHT: "→"
    C_NEXT: "⏭"
    C_PP: "⏯"
    C_BRI_DN: "☀−"
    C_BRI_UP: "☀+"
    C_VOL_DN: "♪−"
    C_VOL_UP: "♪+"
    C_MUTE: "♪×"
  zmk_combos:
    combo_caps_word:
      l: [CAD]
  zmk_preamble: "#define KEYMAP_DRAWER"
